name: Checking for Secrets
on: push
jobs:
  check-secrets:
    name: Checking for Secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Secret Scanner
        uses: secret-scanner/action@0.0.2
  secret-search-job:
    runs-on: 'ubuntu-latest'
    name: Job to scan for secrets
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Execute secret-search
        uses: Hacks4Snacks/secret-search@main
  secret-scanner:
    runs-on: 'ubuntu-latest'
    name: This action scans git repos using awslabs/git-secrets.
    steps:
      - uses: actions/checkout@v2
      - uses: kams-mash/gh-secrets-scanner-action@master